spring.application.name=emailwrapper
server.port=8080

# Gmail SMTP Configuration
# Replace these with your actual email and App Password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonia.codeforce@gmail.com
spring.mail.password=quxu irmy hxyf goxc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# IMAP Configuration
spring.mail.imap.host=imap.gmail.com
spring.mail.imap.port=993
spring.mail.imap.ssl.enable=true